name: BuildBattlePE
version: 0.0.1
api: 5.0.0
author: NurAzliYT
main: cooldogedev\BuildBattle\BuildBattle
website: https://github.com/NurAzliYT/BuildBattlePE
description: "BuildBattle minigame"
permissions:
  buildbattlepe.subcommand.create:
    default: op
  buildbattlepe.subcommand.delete:
    default: op
  buildbattlepe.subcommand.list:
    default: op

  buildbattlepe.subcommand.join:
    default: true
  buildbattlepe.subcommand.quit:
    default: true
