name: BuildBattlePE
main: cooldogedev\BuildBattle\BuildBattle
version: 0.0.1
api: 5.0.0
author: NurAzliYT
description: "BuildBattle minigame"

permissions:
  buildbattlepe.subcommand.create:
    default: op
  buildbattlepe.subcommand.delete:
    default: op
  buildbattlepe.subcommand.list:
    default: op
  buildbattlepe.subcommand.join:
    default: true
  buildbattlepe.subcommand.quit:
    default: true
